//programador: allan stuart virmond
//professor: fernando maia
//instituicao de ensino: colegio estadual do parana
//disciplina: linguagem de programacao
//ide: visualg.2
//data: 16.05.18

//exercicio: 
//executa ate acertar o numero -1



algoritmo "senha"

arquivo "teste.txt"
var
  s:inteiro
inicio
  s<-9
  enquanto s <> -1 faca
    escreval ("Advinhe o número:")
    leia(s)
  fimenquanto
  escreval("Número correto!")
fimalgoritmo
