;programador: allan stuart virmond
;professor: winston sen lun fung
;instituicao de ensino: escola superior politecnica uninter
;disciplina: microprocessadores e microcontroladores
;ide: mplab 7
;microcontrolador: pic16f877a
;dev kit: HJ_5G

;exercicio: 
;botao em modo toggle
;aperta o botao o led liga
;aperta o mesmo botao o led apaga



;APERTA UM BOTAO MANTEM UM LED ACESO
;APERTA O MESMO BOTAO O LED APAGA
;*********************  Defini??o do processador *****************************

			#include p16F877A.inc 
			__config _HS_OSC & _WDT_OFF & _LVP_OFF & _PWRTE_ON 

;************************** Mem?ria de programa ******************************
INTERVALO EQU 7EH
VEZES EQU 7FH

CBLOCK 0X20	
		;CRIANDO PONTEIROS A PARTIR DO ENDERECO 0X20
		;ANTES DO ORG SOMENTE A DECLARACAO, 
		;INICIAR APENAS DEPOIS DE ACESSAR O BANCO CORRETO
	CONTADOR0	;PONTEIRO CONTADOR0 PARA 0X20
	ENDC

 			ORG	0 

RESET
	NOP             
	GOTO SETUP

;***************************** Interrup??o **********************************
 			ORG 4 

;*************************** Inicio do programa ******************************



SETUP	
	BSF STATUS,RP0
		;CONFIGURA O BIT RP0 DO REGISTRADOR
		;STATUS RP0 PARA 1
		;ACESSA O BANK 1 DE MEMORIA
		;S DE SET   
	MOVLW B'00001111'
		;SALVA ESSE BINARIO NO W
	MOVWF TRISB
		;MANDA O WORK PRO TRISB 
		;CONFIGURANDO O TRISB TODO COMO ENTRADA
		;OS BOTOES K4-K1

	MOVLW B'00000000' 
		;PREENCHE O W COM 0 EM TODOS OS BITS
	MOVWF TRISD
		;ENVIA O WORK PARA O TRISD
		;CONFIGURANDO TUDO PARA SAIDA
		;OS LEDS	

	BCF STATUS,RP0
		;configura bit rp0 do registrador
		;status rp0 para 0, acessa o bank0 de memoria;
		;c de clear

	CLRF PORTD

	CLRF CONTADOR0
		;ZERA O CONTADOR0

LOOP
	BTFSS PORTB,0
		;verifica o bit posicional 0 DO PORTB
		;e pula se for 1
		;LINHA 3 POR PADRAO
		;SE O BOTAO K1 ESTIVER APERTADO
	GOTO TOGGLEK1

	RETORNARTOGGLEK1

	BTFSC CONTADOR0,0
		;verifica o bit posicional 0 DO CONTADOR0
		;e pula se for 0
	GOTO ACENDERLED0
	
	RETORNARACENDERLED0



	BTFSS PORTB,1
		;verifica o bit posicional 1 DO PORTB
		;e pula se for 1
		;LINHA 3 POR PADRAO
		;SE O BOTAO K2 ESTIVER APERTADO
	GOTO TOGGLEK2

	RETORNARTOGGLEK2

	BTFSC CONTADOR0,1
		;verifica o bit posicional 1 DO CONTADOR0
		;e pula se for 0
	GOTO ACENDERLED1
	
	RETORNARACENDERLED1



	BTFSS PORTB,2
		;verifica o bit posicional 2 DO PORTB
		;e pula se for 1
		;LINHA 3 POR PADRAO
		;SE O BOTAO K3 ESTIVER APERTADO
	GOTO TOGGLEK3

	RETORNARTOGGLEK3

	BTFSC CONTADOR0,2
		;verifica o bit posicional 2 DO CONTADOR0
		;e pula se for 0
	GOTO ACENDERLED2
	
	RETORNARACENDERLED2



	BTFSS PORTB,3
		;verifica o bit posicional 0 DO PORTB
		;e pula se for 1
		;LINHA 3 POR PADRAO
		;SE O BOTAO K1 ESTIVER APERTADO
	GOTO TOGGLEK4

	RETORNARTOGGLEK4

	BTFSC CONTADOR0,3
		;verifica o bit posicional 0 DO CONTADOR0
		;e pula se for 0
	GOTO ACENDERLED3
	
	RETORNARACENDERLED3





GOTO LOOP



TOGGLEK1
;	CALL AGUARDAR
	BSF PORTD,7
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	BCF PORTD,7

	BTFSC CONTADOR0,0
	GOTO APAGARLED0
	
	BTFSS CONTADOR0,0
	GOTO ACENDERLED0
GOTO RETORNARTOGGLEK1

APAGARLED0
	BCF PORTD,0
		;ZERA O PORTD NO POSICIONAL 0
	BCF CONTADOR0,0
		;DESATIVAR SE ESTIVER ATIVADO
GOTO RETORNARTOGGLEK1

ACENDERLED0
	BSF PORTD,0
	BSF CONTADOR0,0
		;LIGA O LED 0
GOTO RETORNARACENDERLED0



TOGGLEK2
;	CALL AGUARDAR
	BSF PORTD,7
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	BCF PORTD,7

	BTFSC CONTADOR0,1
	GOTO APAGARLED1
	
	BTFSS CONTADOR0,1
	GOTO ACENDERLED1
GOTO RETORNARTOGGLEK2

APAGARLED1
	BCF PORTD,1
		;ZERA O PORTD POSICIONAL 1
	BCF CONTADOR0,1
		;DESATIVAR SE ESTIVER ATIVADO
GOTO RETORNARTOGGLEK2

ACENDERLED1
	BSF PORTD,1
	BSF CONTADOR0,1
		;LIGA O LED 1
GOTO RETORNARACENDERLED1




TOGGLEK3
;	CALL AGUARDAR
	BSF PORTD,7
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	BCF PORTD,7

	BTFSC CONTADOR0,2
	GOTO APAGARLED2
	
	BTFSS CONTADOR0,2
	GOTO ACENDERLED2
GOTO RETORNARTOGGLEK3

APAGARLED2
	BCF PORTD,2
		;ZERA O PORTD NO POSICIONAL 2
	BCF CONTADOR0,2
		;DESATIVAR SE ESTIVER ATIVADO
GOTO RETORNARTOGGLEK3

ACENDERLED2
	BSF PORTD,2
	BSF CONTADOR0,2
		;LIGA O LED 2
GOTO RETORNARACENDERLED2



TOGGLEK4
;	CALL AGUARDAR
	BSF PORTD,7
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	BCF PORTD,7

	BTFSC CONTADOR0,3
	GOTO APAGARLED3
	
	BTFSS CONTADOR0,3
	GOTO ACENDERLED3
GOTO RETORNARTOGGLEK4

APAGARLED3
	BCF PORTD,3
		;ZERA O PORTD NO POSICIONAL 3
	BCF CONTADOR0,3
		;DESATIVAR SE ESTIVER ATIVADO
GOTO RETORNARTOGGLEK4

ACENDERLED3
	BSF PORTD,3
	BSF CONTADOR0,3
		;LIGA O LED 3
GOTO RETORNARACENDERLED3



AGUARDAR
	MOVLW B'11111111'
		;CONTROLA O TEMPO
	MOVWF VEZES

	LACO_VEZES
		MOVLW B'11111111'
		MOVWF INTERVALO
		CALL INTERVALO_US
		DECFSZ VEZES,1
		GOTO LACO_VEZES
	RETURN

	INTERVALO_US
		NOP
		NOP
		DECFSZ INTERVALO,1
		GOTO INTERVALO_US
	RETURN



END
