;programador: allan stuart virmond
;professor: winston sen lun fung
;instituicao de ensino: escola superior politecnica uninter
;disciplina: microprocessadores e microcontroladores
;ide: mplab 7
;microcontrolador: pic16f877a
;dev kit: HJ_5G

;exercicio: 
;Desenvolva  um  circuito  para  controle de  abertura  de um  cofre eletrônicoseguindo os seguintes requisitos.
;Deve gravar uma senha fornecidapelo o usuário.Esta função torna-se ativa com o fornecimento da senha padrão de fábrica ou depois de autenticado com asenha atual.
;Para abrir o cofre é disponibilizado 3 tentativas, caso o usuário erre as   3   tentativas   deve   aguardar   um   tempo   para poder   tentar novamente.
;A senha deve ter 6 dígitosnuméricos.
;O  display  somente  deve  mostrar  a  senha  durante  o  seu  cadastro. Em todos os outros casos a senha deve ser ocultada.
;Quando  aberto  deve  mostrar  por  alguns  instantes  a  mensagem “OPEN” 
;Quando  ordenado  para  travar deve mostrar por alguns  instantes  a mensagem “LOCK”.
;Deve girar um motor demonstrando que foi travado e que foi aberto, simulando a trava do cofre.
;Enquanto o cofre estiver aberto ele deve bipar.
;Orientações:1.Utilize o teclado matricial do kit PIC.2.Utilize o motor de passo para mostrar a posição de travado e aberto
;Escreva   um   relatório   explicando   o   seu   projeto   e   grave   um   vídeo demonstrando o seu funcionamento.Não esqueça de adicionaro diagrama elétrico e o código comentado no seu relatório



;*********************  Defini??o do processador *****************************

			#include p16F877A.inc 
			__config _HS_OSC & _WDT_OFF & _LVP_OFF & _PWRTE_ON 

;************************** Mem?ria de programa ******************************
INTERVALO EQU 7EH
VEZES EQU 7FH

CBLOCK 0X20	
		;CRIANDO PONTEIROS A PARTIR DO ENDERECO 0X20
		;ANTES DO ORG SOMENTE A DECLARACAO, 
		;INICIAR APENAS DEPOIS DE ACESSAR O BANCO CORRETO
	ESTADO	;0X20 ESTADO GERAL DO DISPOSITIVO
	DIGITO1	;0X21 SALVA O DIGITO 1 DA SENHA
	DIGITO2	;0X22 SALVA O DIGITO 2 DA SENHA
	DIGITO3 ;0X23 SALVA O DIGITO 3 DA SENHA
	DIGITO4 ;0X24 SALVA O DIGITO 4 DA SENHA
	DIGITO5 ;0X25 SALVA O DIGITO 5 DA SENHA
	DIGITO6 ;0X26 SALVA O DIGITO 6 DA SENHA
	DIGITOATUAL ;0X27 DIGITANDO QUAL DIGITO DA SENHA..
	DIGITOPRESSIONADO ;0X28 NUMERO PRESSIONADO
	SENHA	;0X29 ACERTOU QUANTOS DIGITOS EM SEQUENCIA..
	ITERACAO	;0X30 USADO NO LACO DE REPETICAO
	DIGITO1AUX	;0X31 CADASTRANDO DIGITO1
	DIGITO2AUX	;0X32 CADASTRANDO DIGITO2
	DIGITO3AUX	;0X33 CADASTRANDO DIGITO3
	DIGITO4AUX	;0X34 CADASTRANDO DIGITO4
	DIGITO5AUX	;0X35 CADASTRANDO DIGITO5
	DIGITO6AUX	;0X36 CADASTRANDO DIGITO6
	TENTATIVAS	;0X37 NUMERO DE TENTATIVAS DE ABRIR O COFRE
	ENDC

 			ORG	0 

RESET
	NOP             
	GOTO SETUP

;***************************** Interrup??o **********************************
 			ORG 4 

;*************************** Inicio do programa ******************************



SETUP	
	BSF STATUS,RP0
		;CONFIGURA O BIT RP0 DO REGISTRADOR
		;STATUS RP0 PARA 1
		;ACESSA O BANK 1 DE MEMORIA
		;S DE SET
	MOVLW B'00000000'
		;MOVE ESSE BINARIO PARA O WORK
	MOVWF TRISA
		;MOVE DO WORK PRO TRISA
		;SELECAO DE DISPLAY
	MOVLW B'00001111'
		;SALVA ESSE BINARIO NO W
	MOVWF TRISB
		;MANDA O WORK PRO TRISB 
		;CONFIGURANDO COMO ENTRADA 1 SAIDA 0 NO TRISB
		;TECLADO MATRICIAL
	MOVLW B'00000000'
		;MANDA ESSE BINARIO PARA O WORK
	MOVWF TRISC
		;CONFIGURA TODO TRISC PARA SAIDA
		;MOTOR
	MOVLW B'00000000' 
		;PREENCHE O W COM 0 EM TODOS OS BITS
	MOVWF TRISD
		;ENVIA O WORK PARA O TRISD
		;CONFIGURANDO O TRISD TODO PARA SAIDA 0
		;SEGMENTOS	
	MOVLW B'00000000' 
		;PREENCHE O W COM 0 EM TODOS OS BITS
	MOVWF TRISE
		;ENVIA O WORK PARA O TRISE
		;CONFIGURANDO O TRISD TODO PARA SAIDA 0
		;SEGMENTOS	


	BCF STATUS,RP0
		;configura bit rp0 do registrador
		;status rp0 para 0, acessa o bank0 de memoria
		;c de clear
		
		;ZERA ESSES REGISTRADORES
	CLRW
	CLRF PORTA
	CLRF PORTB
	CLRF PORTC
	CLRF PORTD
	CLRF PORTE
	CLRF ESTADO
	CLRF DIGITO1
	CLRF DIGITO2
	CLRF DIGITO3
	CLRF DIGITO4
	CLRF DIGITO5
	CLRF DIGITO6
	CLRF DIGITOATUAL
	CLRF SENHA
	CLRF DIGITOPRESSIONADO
	CLRF VEZES
	CLRF INTERVALO
	CLRF ITERACAO
	CLRF DIGITO1AUX
	CLRF DIGITO2AUX
	CLRF DIGITO3AUX
	CLRF DIGITO4AUX
	CLRF DIGITO5AUX
	CLRF DIGITO6AUX
	CLRF TENTATIVAS

	;CARREGA O ESTADO PADRAO INICIAL DO COFRE
	;FECHANDO
	MOVLW B'00000010'
	MOVWF ESTADO

		;RECUPERA DA MEMORIA AUXILIAR O DIGITO1
	BSF     STATUS,RP1     ;
	BCF     STATUS,RP0     ; ACESSA O Bank 2
	MOVLW D'1'			   ; ENDERECO 1 DA EEPROM
	MOVWF   EEADR          ; Address to read
	BSF     STATUS,RP0     ; Bank 3
	BCF     EECON1,EEPGD   ; Point to Data; memory
	BSF     EECON1,RD      ; EE Read
	BCF     STATUS,RP0     ; Bank 2 
	MOVF    EEDATA,W       ; W = EEDATA
	BCF STATUS,RP1		   ; BANK 0
	MOVWF DIGITO1

		;RECUPERA DA MEMORIA AUXILIAR O DIGITO2
	BSF     STATUS,RP1     ;
	BCF     STATUS,RP0     ; ACESSA O Bank 2
	MOVLW D'2'			   ; ENDERECO 1 DA EEPROM
	MOVWF   EEADR          ; Address to read
	BSF     STATUS,RP0     ; Bank 3
	BCF     EECON1,EEPGD   ; Point to Data; memory
	BSF     EECON1,RD      ; EE Read
	BCF     STATUS,RP0     ; Bank 2 
	MOVF    EEDATA,W       ; W = EEDATA
	BCF STATUS,RP1		   ; BANK 0
	MOVWF DIGITO2

		;RECUPERA DA MEMORIA AUXILIAR O DIGITO3
	BSF     STATUS,RP1     ;
	BCF     STATUS,RP0     ; ACESSA O Bank 2
	MOVLW D'3'			   ; ENDERECO 1 DA EEPROM
	MOVWF   EEADR          ; Address to read
	BSF     STATUS,RP0     ; Bank 3
	BCF     EECON1,EEPGD   ; Point to Data; memory
	BSF     EECON1,RD      ; EE Read
	BCF     STATUS,RP0     ; Bank 2 
	MOVF    EEDATA,W       ; W = EEDATA
	BCF STATUS,RP1		   ; BANK 0
	MOVWF DIGITO3

		;RECUPERA DA MEMORIA AUXILIAR O DIGITO4
	BSF     STATUS,RP1     ;
	BCF     STATUS,RP0     ; ACESSA O Bank 2
	MOVLW D'4'			   ; ENDERECO 1 DA EEPROM
	MOVWF   EEADR          ; Address to read
	BSF     STATUS,RP0     ; Bank 3
	BCF     EECON1,EEPGD   ; Point to Data; memory
	BSF     EECON1,RD      ; EE Read
	BCF     STATUS,RP0     ; Bank 2 
	MOVF    EEDATA,W       ; W = EEDATA
	BCF STATUS,RP1		   ; BANK 0
	MOVWF DIGITO4

		;RECUPERA DA MEMORIA AUXILIAR O DIGITO5
	BSF     STATUS,RP1     ;
	BCF     STATUS,RP0     ; ACESSA O Bank 2
	MOVLW D'5'			   ; ENDERECO 1 DA EEPROM
	MOVWF   EEADR          ; Address to read
	BSF     STATUS,RP0     ; Bank 3
	BCF     EECON1,EEPGD   ; Point to Data; memory
	BSF     EECON1,RD      ; EE Read
	BCF     STATUS,RP0     ; Bank 2 
	MOVF    EEDATA,W       ; W = EEDATA
	BCF STATUS,RP1		   ; BANK 0
	MOVWF DIGITO5

		;RECUPERA DA MEMORIA AUXILIAR O DIGITO6
	BSF     STATUS,RP1     ;
	BCF     STATUS,RP0     ; ACESSA O Bank 2
	MOVLW D'6'			   ; ENDERECO 1 DA EEPROM
	MOVWF   EEADR          ; Address to read
	BSF     STATUS,RP0     ; Bank 3
	BCF     EECON1,EEPGD   ; Point to Data; memory
	BSF     EECON1,RD      ; EE Read
	BCF     STATUS,RP0     ; Bank 2 
	MOVF    EEDATA,W       ; W = EEDATA
	BCF STATUS,RP1		   ; BANK 0
	MOVWF DIGITO6



LOOP
		;LER BOTOES A, B
		;A ABRIR
		;B FECHAR
	MOVLW B'10111111'
	MOVWF PORTB
	BTFSS PORTB,2	;A
	CALL TECLAA
	BTFSS PORTB,3	;B
	CALL TECLAB

	BTFSC ESTADO,0
		GOTO ABRIR
		GOTO FECHAR
		RABRIR
		RFECHAR

	MOVLW D'6'
	SUBWF SENHA,0
	BTFSC STATUS,Z
	BSF ESTADO,3

	BTFSC ESTADO,4
	GOTO NOVASENHA
	RNOVASENHA

		;VARRER TECLADO MATRICIAL DE 0-9
	MOVLW B'11101111'
	MOVWF PORTB
	BTFSS PORTB,0
		CALL TECLA0
	BTFSS PORTB,1
		CALL TECLA1
	BTFSS PORTB,2
		CALL TECLA2
	BTFSS PORTB,3
		CALL TECLA3

	MOVLW B'11011111'
	MOVWF PORTB
	BTFSS PORTB,0
		CALL TECLA4
	BTFSS PORTB,1
		CALL TECLA5
	BTFSS PORTB,2
		CALL TECLA6
	BTFSS PORTB,3
		CALL TECLA7

	MOVLW B'10111111'
	MOVWF PORTB
		BTFSS PORTB,0
		CALL TECLA8
	BTFSS PORTB,1
		CALL TECLA9


GOTO LOOP



TECLA0
	CALL PRESSIONOU

	BTFSS ESTADO,0
	CALL TECLA0FECHADO

	BTFSC ESTADO,4
	CALL TECLA0ABERTO
RETURN

TECLA0FECHADO
	INCF DIGITOATUAL,1
	CLRW
	MOVWF DIGITOPRESSIONADO
	CALL COMPARAR
RETURN

TECLA0ABERTO
	MOVLW B'00100000'
	MOVWF PORTA
	MOVLW B'00111111'  ; 0
	MOVWF PORTD

	INCF SENHA,1

	CLRW
	MOVWF DIGITOATUAL
	
	CALL ATRIBUIRDIGITO

RETURN


TECLA1
	CALL PRESSIONOU

	BTFSS ESTADO,0
	CALL TECLA1FECHADO

	BTFSC ESTADO,4
	CALL TECLA1ABERTO
RETURN

TECLA1FECHADO
	INCF DIGITOATUAL,1
	MOVLW D'1'
	MOVWF DIGITOPRESSIONADO
	CALL COMPARAR
RETURN

TECLA1ABERTO
	MOVLW B'00100000'
	MOVWF PORTA
	MOVLW B'00000110'  ; 1
	MOVWF PORTD

	INCF SENHA,1

	MOVLW D'1'
	MOVWF DIGITOATUAL
	
	CALL ATRIBUIRDIGITO
RETURN


TECLA2
	CALL PRESSIONOU

	BTFSS ESTADO,0
	CALL TECLA2FECHADO

	BTFSC ESTADO,4
	CALL TECLA2ABERTO
RETURN

TECLA2FECHADO
	INCF DIGITOATUAL,1
	MOVLW D'2'
	MOVWF DIGITOPRESSIONADO
	CALL COMPARAR
RETURN

TECLA2ABERTO
	MOVLW B'00100000'
	MOVWF PORTA
	MOVLW B'01011011'  ; 2
	MOVWF PORTD

	INCF SENHA,1

	MOVLW D'2'
	MOVWF DIGITOATUAL
	
	CALL ATRIBUIRDIGITO
RETURN


TECLA3
	CALL PRESSIONOU

	BTFSS ESTADO,0
	CALL TECLA3FECHADO

	BTFSC ESTADO,4
	CALL TECLA3ABERTO
RETURN

TECLA3FECHADO
	INCF DIGITOATUAL,1
	MOVLW D'3'
	MOVWF DIGITOPRESSIONADO
	CALL COMPARAR
RETURN

TECLA3ABERTO
	MOVLW B'00100000'
	MOVWF PORTA
	MOVLW B'01001111'  ; 3
	MOVWF PORTD

	INCF SENHA,1

	MOVLW D'3'
	MOVWF DIGITOATUAL
	
	CALL ATRIBUIRDIGITO
RETURN


TECLA4
	CALL PRESSIONOU

	BTFSS ESTADO,0
	CALL TECLA4FECHADO

	BTFSC ESTADO,4
	CALL TECLA4ABERTO
RETURN

TECLA4FECHADO
	INCF DIGITOATUAL,1
	MOVLW D'4'
	MOVWF DIGITOPRESSIONADO
	CALL COMPARAR
RETURN

TECLA4ABERTO
	MOVLW B'00100000'
	MOVWF PORTA
	MOVLW B'01100110'  ; 4
	MOVWF PORTD

	INCF SENHA,1

	MOVLW D'4'
	MOVWF DIGITOATUAL
	
	CALL ATRIBUIRDIGITO
RETURN


TECLA5
	CALL PRESSIONOU

	BTFSS ESTADO,0
	CALL TECLA5FECHADO

	BTFSC ESTADO,4
	CALL TECLA5ABERTO
RETURN

TECLA5FECHADO
	INCF DIGITOATUAL,1
	MOVLW D'5'
	MOVWF DIGITOPRESSIONADO
	CALL COMPARAR
RETURN


TECLA5ABERTO
	MOVLW B'00100000'
	MOVWF PORTA
	MOVLW B'01101101'  ; 5
	MOVWF PORTD

	INCF SENHA,1

	MOVLW D'5'
	MOVWF DIGITOATUAL
	
	CALL ATRIBUIRDIGITO
RETURN


TECLA6
	CALL PRESSIONOU

	BTFSS ESTADO,0
	CALL TECLA6FECHADO

	BTFSC ESTADO,4
	CALL TECLA6ABERTO
RETURN

TECLA6FECHADO
	INCF DIGITOATUAL,1
	MOVLW D'6'
	MOVWF DIGITOPRESSIONADO
	CALL COMPARAR
RETURN

TECLA6ABERTO
	MOVLW B'00100000'
	MOVWF PORTA
	MOVLW B'01111101'  ; 6
	MOVWF PORTD

	INCF SENHA,1

	MOVLW D'6'
	MOVWF DIGITOATUAL
	
	CALL ATRIBUIRDIGITO
RETURN


TECLA7
	CALL PRESSIONOU

	BTFSS ESTADO,0
	CALL TECLA7FECHADO

	BTFSC ESTADO,4
	CALL TECLA7ABERTO
RETURN

TECLA7FECHADO
	INCF DIGITOATUAL,1
	MOVLW D'7'
	MOVWF DIGITOPRESSIONADO
	CALL COMPARAR
RETURN

TECLA7ABERTO
	MOVLW B'00100000'
	MOVWF PORTA
	MOVLW B'00000111'  ; 7
	MOVWF PORTD

	INCF SENHA,1

	MOVLW D'7'
	MOVWF DIGITOATUAL
	
	CALL ATRIBUIRDIGITO
RETURN


TECLA8
	CALL PRESSIONOU

	BTFSS ESTADO,0
	CALL TECLA8FECHADO

	BTFSC ESTADO,4
	CALL TECLA8ABERTO
RETURN

TECLA8FECHADO
	INCF DIGITOATUAL,1
	MOVLW D'8'
	MOVWF DIGITOPRESSIONADO
	CALL COMPARAR
RETURN

TECLA8ABERTO
	MOVLW B'00100000'
	MOVWF PORTA
	MOVLW B'01111111'  ; 8
	MOVWF PORTD

	INCF SENHA,1

	MOVLW D'8'
	MOVWF DIGITOATUAL
	
	CALL ATRIBUIRDIGITO
RETURN


TECLA9
	CALL PRESSIONOU

	BTFSS ESTADO,0
	CALL TECLA9FECHADO

	BTFSC ESTADO,4
	CALL TECLA9ABERTO
RETURN

TECLA9FECHADO
	INCF DIGITOATUAL,1
	MOVLW D'9'
	MOVWF DIGITOPRESSIONADO
	CALL COMPARAR
RETURN

TECLA9ABERTO
	MOVLW B'00100000'
	MOVWF PORTA
	MOVLW B'01101111'  ; 9
	MOVWF PORTD

	INCF SENHA,1

	MOVLW D'9'
	MOVWF DIGITOATUAL
	
	CALL ATRIBUIRDIGITO
RETURN


TECLAA
	CALL PRESSIONOU

	MOVLW B'11111111'
	MOVWF ITERACAO 	
	INCF TENTATIVAS,1
	MOVLW D'4'
	SUBWF TENTATIVAS,W	
	BTFSC STATUS,Z
	CALL BLOQUEARTEMPORARIAMENTE	

		;SE O COFRE ESTIVER ABERTO 
		;VAI PRA FUNCAO DE TROCA DE SENHA
	BTFSC ESTADO,0
	BSF ESTADO,4

		;SE A SENHA ESTIVER ERRADA NAO ABRE
	BTFSC ESTADO,3
	BSF ESTADO,0

		;MARCAR COMO ABRINDO SE ESTIVER COM A SENHA CERTA
	BTFSC ESTADO,3
	BSF ESTADO,2

;		;MARCA CODE COMO NAO EXIBIDO
	BTFSC ESTADO,0
	BSF ESTADO,5

	CALL PRESSIONOU

RETURN


TECLAB
	CALL PRESSIONOU

		;MARCAR COMO FECHADO E ZERAR A SENHA
	BCF ESTADO,0
	CALL ZERARTENTATIVA

		;MARCAR COMO FECHANDO
	BSF ESTADO,1

		;DESLIGAR MODO DE ALTERAR SENHA
	BCF ESTADO,4
RETURN


ABRIR
		;LIGAR BUZZER
	BCF PORTE,0
		;SE JA ESTIVER ABERTO NAO ABRIR NOVAMENTE
	BTFSS ESTADO,2
		GOTO RABRIR

		;SE ESTIVER CADASTRANDO SENHA NAO ABRIR NOVAMENTE
	BTFSC ESTADO,4
		GOTO RABRIR

		;GIRAR O MOTOR 255 PASSOS
	MOVLW B'00111111'
	MOVWF ITERACAO
	MOTORABRIRPASSO
	CALL MOTORABRIR
	DECFSZ ITERACAO,1
	GOTO MOTORABRIRPASSO

		;ESCREVER OPEN 255 VEZES
	MOVLW B'11111111'
	MOVWF ITERACAO
	ESCREVEROPENPASSO
	CALL ESCREVEROPEN
	DECFSZ ITERACAO,1
	GOTO ESCREVEROPENPASSO

		;NAO ESTA MAIS ABRINDO
	BCF ESTADO,2
GOTO RABRIR


FECHAR
		;SE JA ESTIVER FECHADO NAO FECHAR NOVAMENTE
	BTFSS ESTADO,1
		GOTO RFECHAR

		;DESLIGAR BUZZER
	BSF PORTE,0

		;GIRAR O MOTOR 255 PASSOS
	MOVLW B'00111111'
	MOVWF ITERACAO
	MOTORFECHARPASSO
	CALL MOTORFECHAR
	DECFSZ ITERACAO,1
	GOTO MOTORFECHARPASSO

		;ESCREVER LOCK 255 VEZES
	MOVLW B'11111111'
	MOVWF ITERACAO
	ESCREVERLOCKPASSO
	CALL ESCREVERLOCK
	DECFSZ ITERACAO,1
	GOTO ESCREVERLOCKPASSO

		;NAO ESTA MAIS FECHANDO
	BCF ESTADO,1
GOTO RFECHAR


MOTORABRIR

	MOVLW B'00000001'
	MOVWF PORTC
	CALL AGUARDARM


	MOVLW B'00000010'
	MOVWF PORTC
	CALL AGUARDARM


	MOVLW B'00000100'
	MOVWF PORTC
	CALL AGUARDARM

	MOVLW B'00001000'
	MOVWF PORTC
	CALL AGUARDARM

	CLRF PORTC
RETURN


MOTORFECHAR

	MOVLW B'00000001'
	MOVWF PORTC
	CALL AGUARDARM

	MOVLW B'00001000'
	MOVWF PORTC
	CALL AGUARDARM

	MOVLW B'00000100'
	MOVWF PORTC
	CALL AGUARDARM

	MOVLW B'00000010'
	MOVWF PORTC
	CALL AGUARDARM

	CLRF PORTC
RETURN


PRESSIONOU
			;LIGA O PONTO DO DISPLAY 0 PRA SABER QUE APERTOU ALGUM BOTAO
	MOVLW B'00100000'
	MOVWF PORTA
	MOVLW B'10000000'
	MOVWF PORTD
	CALL AGUARDARB
	CALL AGUARDARB
	CALL AGUARDARB
	CLRF PORTA
	CLRF PORTD
RETURN


COMPARAR
		;CHAMA COMPARARN DE ACORDO COM QUAL E O DIGITO DA SEQUENCIA DE SENHA
	MOVLW D'1'
	SUBWF DIGITOATUAL,0	
	BTFSC STATUS,Z
	CALL COMPARAR1

	MOVLW D'2'
	SUBWF DIGITOATUAL,0	
	BTFSC STATUS,Z
	CALL COMPARAR2

	MOVLW D'3'
	SUBWF DIGITOATUAL,0	
	BTFSC STATUS,Z
	CALL COMPARAR3

	MOVLW D'4'
	SUBWF DIGITOATUAL,0	
	BTFSC STATUS,Z
	CALL COMPARAR4

	MOVLW D'5'
	SUBWF DIGITOATUAL,0	
	BTFSC STATUS,Z
	CALL COMPARAR5

	MOVLW D'6'
	SUBWF DIGITOATUAL,0	
	BTFSC STATUS,Z
	CALL COMPARAR6

RETURN

	;COMPARA O DIGITO PRESSIONADO COM O DIGITO DA POSICAO DA SENHA
	;SE TIVER CORRETO MARCA COMO CORRETO PARA CONFERIR O PROXIMO DIGITO
	;SE ESTIVER ERRADO ZERA A TENTATIVA
COMPARAR1
	MOVF DIGITOPRESSIONADO,0
	SUBWF DIGITO1,0
	BTFSC STATUS,Z
	GOTO DIGITOCORRETO1
	CALL ZERARTENTATIVA
	RDIGITOCORRETO1
RETURN


COMPARAR2
	MOVF DIGITOPRESSIONADO,0
	SUBWF DIGITO2,0
	BTFSC STATUS,Z
	GOTO DIGITOCORRETO2
	CALL ZERARTENTATIVA
	RDIGITOCORRETO2
RETURN


COMPARAR3
	MOVF DIGITOPRESSIONADO,0
	SUBWF DIGITO3,0
	BTFSC STATUS,Z
	GOTO DIGITOCORRETO3
	CALL ZERARTENTATIVA
	RDIGITOCORRETO3
RETURN


COMPARAR4
	MOVF DIGITOPRESSIONADO,0
	SUBWF DIGITO4,0
	BTFSC STATUS,Z
	GOTO DIGITOCORRETO4
	CALL ZERARTENTATIVA
	RDIGITOCORRETO4
RETURN


COMPARAR5
	MOVF DIGITOPRESSIONADO,0
	SUBWF DIGITO5,0
	BTFSC STATUS,Z
	GOTO DIGITOCORRETO5
	CALL ZERARTENTATIVA
	RDIGITOCORRETO5
RETURN


COMPARAR6
	MOVF DIGITOPRESSIONADO,0
	SUBWF DIGITO6,0
	BTFSC STATUS,Z
	GOTO DIGITOCORRETO6
	CALL ZERARTENTATIVA
	RDIGITOCORRETO6
RETURN


ZERARTENTATIVA
		;ZERA O PROGRESSO DA CADEIA DE DIGITACAO DE SENHA
	CLRF SENHA
	CLRF DIGITOATUAL
	BCF ESTADO,3
RETURN


DIGITOCORRETO1
	INCF SENHA,1
GOTO RDIGITOCORRETO1


DIGITOCORRETO2
	INCF SENHA,1
GOTO RDIGITOCORRETO2


DIGITOCORRETO3
	INCF SENHA,1
GOTO RDIGITOCORRETO3


DIGITOCORRETO4
	INCF SENHA,1
GOTO RDIGITOCORRETO4


DIGITOCORRETO5
	INCF SENHA,1
GOTO RDIGITOCORRETO5


DIGITOCORRETO6
	INCF SENHA,1
GOTO RDIGITOCORRETO6


ESCREVEROPEN
		;ESCREVER OPEN
	MOVLW B'00100000'
	MOVWF PORTA
	MOVLW B'00111111' ; O	
	MOVWF PORTD
	CALL AGUARDAR
	MOVLW B'00010000'
	MOVWF PORTA
	MOVLW B'01110011'  ; P	
	MOVWF PORTD
	CALL AGUARDAR
	MOVLW B'00001000'
	MOVWF PORTA
	MOVLW B'01111001'  ; E	
	MOVWF PORTD
	CALL AGUARDAR
	MOVLW B'00000100'
	MOVWF PORTA
	MOVLW B'01010100'  ; n	
	MOVWF PORTD
	CALL AGUARDAR
	CLRF PORTA
	CLRF PORTD
RETURN


ESCREVERLOCK
		;ESCREVER LOCK
	MOVLW B'00100000'
	MOVWF PORTA
	MOVLW B'00111000'  ; L	
	MOVWF PORTD
	CALL AGUARDAR
	MOVLW B'00010000'
	MOVWF PORTA
	MOVLW B'00111111'  ; 0	
	MOVWF PORTD
	CALL AGUARDAR
	MOVLW B'00001000'
	MOVWF PORTA
	MOVLW B'00111001'  ; C
	MOVWF PORTD
	CALL AGUARDAR
	MOVLW B'00000100'
	MOVWF PORTA
	MOVLW B'01110000'  ; K
	MOVWF PORTD
	CALL AGUARDAR
	CLRF PORTA
	CLRF PORTD
RETURN


ESCREVERCODE
		;ESCREVER CODE
	ESCREVERCODEPASSO
	MOVLW B'00100000'
	MOVWF PORTA
	MOVLW B'00111001'  ; C
	MOVWF PORTD
	CALL AGUARDAR
	MOVLW B'00010000'
	MOVWF PORTA
	MOVLW B'00111111'  ; 0	
	MOVWF PORTD
	CALL AGUARDAR
	MOVLW B'00001000'
	MOVWF PORTA
	MOVLW B'01011110'  ; D
	MOVWF PORTD
	CALL AGUARDAR
	MOVLW B'00000100'
	MOVWF PORTA
	MOVLW B'01111001'  ; E
	MOVWF PORTD
	CALL AGUARDAR
	CLRF PORTA
	CLRF PORTD
		;ESCREVER CODE ITERACAO VEZES
	DECFSZ ITERACAO,1
	GOTO ESCREVERCODEPASSO

		;0 JA ESCREVEU CODE 
		;1 ESCREVENDO CODE	
	BCF ESTADO,5
		;PARA INICIAR O CADASTRO DE SENHA
	CLRF SENHA
RETURN


NOVASENHA

		; AJUSTA QUANTAS VEZES ESCREVER CODE
	MOVLW B'11111111'
	MOVWF ITERACAO

	BTFSC ESTADO,5
	CALL ESCREVERCODE

		;A PARTIR DAQUI SE ESTIVER SALVO OS 6 DIGITOS AUX VAI SALVAR A SENHA
	MOVLW D'6'
	SUBWF SENHA,0
	BTFSC STATUS,Z
	CALL SALVARSENHA
GOTO RNOVASENHA


ATRIBUIRDIGITO
	MOVLW D'1'
	SUBWF SENHA,0
	BTFSC STATUS,Z
	CALL ATRIBUIRDIGITO1

	MOVLW D'2'
	SUBWF SENHA,0
	BTFSC STATUS,Z
	CALL ATRIBUIRDIGITO2

	MOVLW D'3'
	SUBWF SENHA,0
	BTFSC STATUS,Z
	CALL ATRIBUIRDIGITO3

	MOVLW D'4'
	SUBWF SENHA,0
	BTFSC STATUS,Z
	CALL ATRIBUIRDIGITO4

	MOVLW D'5'
	SUBWF SENHA,0
	BTFSC STATUS,Z
	CALL ATRIBUIRDIGITO5

	MOVLW D'6'
	SUBWF SENHA,0
	BTFSC STATUS,Z
	CALL ATRIBUIRDIGITO6

RETURN


ATRIBUIRDIGITO1
	MOVF DIGITOATUAL,0
	MOVWF DIGITO1AUX
RETURN

ATRIBUIRDIGITO2
	MOVF DIGITOATUAL,0
	MOVWF DIGITO2AUX
RETURN

ATRIBUIRDIGITO3
	MOVF DIGITOATUAL,0
	MOVWF DIGITO3AUX
RETURN

ATRIBUIRDIGITO4
	MOVF DIGITOATUAL,0
	MOVWF DIGITO4AUX
RETURN

ATRIBUIRDIGITO5
	MOVF DIGITOATUAL,0
	MOVWF DIGITO5AUX
RETURN

ATRIBUIRDIGITO6
	MOVF DIGITOATUAL,0
	MOVWF DIGITO6AUX
RETURN


SALVARSENHA
		;SALVA A SENHA AUXILIAR NA MEMORIA PRINCIPAL
		;SALVA O AUXILIAR NO W E MANDA DO W PRA MEMORIA PRINCIPAL
	MOVF DIGITO1AUX,0
	MOVWF DIGITO1

	MOVF DIGITO2AUX,0
	MOVWF DIGITO2

	MOVF DIGITO3AUX,0
	MOVWF DIGITO3

	MOVF DIGITO4AUX,0
	MOVWF DIGITO4

	MOVF DIGITO5AUX,0
	MOVWF DIGITO5

	MOVF DIGITO6AUX,0
	MOVWF DIGITO6


		;SALVANDO DIGITO 1 DA SENHA NA MEMORIA AUXILIAR
	MOVF DIGITO1AUX,W
	BSF    STATUS,RP1
	BSF    STATUS,RP0	;BANK3
	BTFSC EECON1,WR      ;Wait for write
	GOTO   $-1            ;to complete
	BCF    STATUS,  RP0    ;Bank 2
	MOVWF EEDATA         ;to write
;	MOVF   DATA_EE_ADDR,W ;Data Memory
	MOVLW D'1'
	MOVWF EEADR          ;Address to write
	BSF    STATUS,RP0     ;Bank 3
	BCF    EECON1,EEPGD   ;Point to DATA ;memory
	BSF    EECON1,WREN    ;Enable writes
	BCF    INTCON,GIE     ;Disable INTs.
	MOVLW H'55'            ; 
	MOVWF EECON2         ;Write 55h
	MOVLW H'AA'            ; 
	MOVWF EECON2         ;Write AAh
	BSF    EECON1,WR      ;Set WR bit to;begin write
	BSF    INTCON,GIE     ;Enable INTs.
	BCF    EECON1,WREN    ;Disable writes

		;SALVANDO DIGITO 2 DA SENHA NA MEMORIA AUXILIAR
	BCF STATUS,RP0
	BCF STATUS,RP1	;BANK0
	MOVF DIGITO2AUX,W
	BSF    STATUS,RP1
	BSF    STATUS,RP0	;BANK3
	BTFSC EECON1,WR      ;Wait for write
	GOTO   $-1            ;to complete
	BCF    STATUS,  RP0    ;Bank 2
	MOVWF EEDATA         ;to write
;	MOVF   DATA_EE_ADDR,W ;Data Memory
	MOVLW D'2'
	MOVWF EEADR          ;Address to write
	BSF    STATUS,RP0     ;Bank 3
	BCF    EECON1,EEPGD   ;Point to DATA ;memory
	BSF    EECON1,WREN    ;Enable writes
	BCF    INTCON,GIE     ;Disable INTs.
	MOVLW H'55'            ; 
	MOVWF EECON2         ;Write 55h
	MOVLW H'AA'            ; 
	MOVWF EECON2         ;Write AAh
	BSF    EECON1,WR      ;Set WR bit to;begin write
	BSF    INTCON,GIE     ;Enable INTs.
	BCF    EECON1,WREN    ;Disable writes

		;SALVANDO DIGITO 3 DA SENHA NA MEMORIA AUXILIAR
	BCF STATUS,RP0
	BCF STATUS,RP1	;BANK0
	MOVF DIGITO3AUX,W
	BSF    STATUS,RP1
	BSF    STATUS,RP0	;BANK3
	BTFSC EECON1,WR      ;Wait for write
	GOTO   $-1            ;to complete
	BCF    STATUS,  RP0    ;Bank 2
	MOVWF EEDATA         ;to write
;	MOVF   DATA_EE_ADDR,W ;Data Memory
	MOVLW D'3'
	MOVWF EEADR          ;Address to write
	BSF    STATUS,RP0     ;Bank 3
	BCF    EECON1,EEPGD   ;Point to DATA ;memory
	BSF    EECON1,WREN    ;Enable writes
	BCF    INTCON,GIE     ;Disable INTs.
	MOVLW H'55'            ; 
	MOVWF EECON2         ;Write 55h
	MOVLW H'AA'            ; 
	MOVWF EECON2         ;Write AAh
	BSF    EECON1,WR      ;Set WR bit to;begin write
	BSF    INTCON,GIE     ;Enable INTs.
	BCF    EECON1,WREN    ;Disable writes

		;SALVANDO DIGITO 4 DA SENHA NA MEMORIA AUXILIAR
	BCF STATUS,RP0
	BCF STATUS,RP1	;BANK0
	MOVF DIGITO4AUX,W
	BSF    STATUS,RP1
	BSF    STATUS,RP0	;BANK3
	BTFSC EECON1,WR      ;Wait for write
	GOTO   $-1            ;to complete
	BCF    STATUS,  RP0    ;Bank 2
	MOVWF EEDATA         ;to write
;	MOVF   DATA_EE_ADDR,W ;Data Memory
	MOVLW D'4'
	MOVWF EEADR          ;Address to write
	BSF    STATUS,RP0     ;Bank 3
	BCF    EECON1,EEPGD   ;Point to DATA ;memory
	BSF    EECON1,WREN    ;Enable writes
	BCF    INTCON,GIE     ;Disable INTs.
	MOVLW H'55'            ; 
	MOVWF EECON2         ;Write 55h
	MOVLW H'AA'            ; 
	MOVWF EECON2         ;Write AAh
	BSF    EECON1,WR      ;Set WR bit to;begin write
	BSF    INTCON,GIE     ;Enable INTs.
	BCF    EECON1,WREN    ;Disable writes

		;SALVANDO DIGITO 5 DA SENHA NA MEMORIA AUXILIAR
	BCF STATUS,RP0
	BCF STATUS,RP1	;BANK0
	MOVF DIGITO5AUX,W
	BSF    STATUS,RP1
	BSF    STATUS,RP0	;BANK3
	BTFSC EECON1,WR      ;Wait for write
	GOTO   $-1            ;to complete
	BCF    STATUS,  RP0    ;Bank 2
	MOVWF EEDATA         ;to write
;	MOVF   DATA_EE_ADDR,W ;Data Memory
	MOVLW D'5'
	MOVWF EEADR          ;Address to write
	BSF    STATUS,RP0     ;Bank 3
	BCF    EECON1,EEPGD   ;Point to DATA ;memory
	BSF    EECON1,WREN    ;Enable writes
	BCF    INTCON,GIE     ;Disable INTs.
	MOVLW H'55'            ; 
	MOVWF EECON2         ;Write 55h
	MOVLW H'AA'            ; 
	MOVWF EECON2         ;Write AAh
	BSF    EECON1,WR      ;Set WR bit to;begin write
	BSF    INTCON,GIE     ;Enable INTs.
	BCF    EECON1,WREN    ;Disable writes

		;SALVANDO DIGITO 6 DA SENHA NA MEMORIA AUXILIAR
	BCF STATUS,RP0
	BCF STATUS,RP1	;BANK0
	MOVF DIGITO6AUX,W
	BSF    STATUS,RP1
	BSF    STATUS,RP0	;BANK3
	BTFSC EECON1,WR      ;Wait for write
	GOTO   $-1            ;to complete
	BCF    STATUS,  RP0    ;Bank 2
	MOVWF EEDATA         ;to write
;	MOVF   DATA_EE_ADDR,W ;Data Memory
	MOVLW D'6'
	MOVWF EEADR          ;Address to write
	BSF    STATUS,RP0     ;Bank 3
	BCF    EECON1,EEPGD   ;Point to DATA ;memory
	BSF    EECON1,WREN    ;Enable writes
	BCF    INTCON,GIE     ;Disable INTs.
	MOVLW H'55'            ; 
	MOVWF EECON2         ;Write 55h
	MOVLW H'AA'            ; 
	MOVWF EECON2         ;Write AAh
	BSF    EECON1,WR      ;Set WR bit to;begin write
	BSF    INTCON,GIE     ;Enable INTs.
	BCF    EECON1,WREN    ;Disable writes

		;VOLTA PRO BANK0
	BCF STATUS,RP0
	BCF STATUS,RP1

		;ENCERRA O MODO DE CADASTRO DE SENHA
	BCF ESTADO,4
RETURN


BLOQUEARTEMPORARIAMENTE
	BLOQUEARTEMPORARIAMENTEPASSO
	CALL AGUARDARB
	DECFSZ ITERACAO,1
	GOTO BLOQUEARTEMPORARIAMENTEPASSO

		;ZERAR AS TENTATIVAS
	MOVLW D'1'
	MOVWF TENTATIVAS
RETURN



AGUARDARB
		;PRO BOTAO DEIXAR NO MAXIMO 
	MOVLW B'11111111'
		;CONTROLA O TEMPO
	MOVWF VEZES
	GOTO LACO_VEZES

AGUARDARM
		;PRO MOTOR ALGO ENTRE 
		;B'00111111' E B'00011111'
		;MEDIA D'47'
		;FICOU BOM EM D'56' MAS AS VEZES NAO RESPONDE AO FECHAR	
	MOVLW D'60'
		;CONTROLA O TEMPO
	MOVWF VEZES
	GOTO LACO_VEZES

AGUARDAR
		;PRO DISPLAY
		;B'00000111'
	MOVLW B'00000111'
		;CONTROLA O TEMPO
	MOVWF VEZES

	LACO_VEZES
		MOVLW B'11111111'
		MOVWF INTERVALO
		CALL INTERVALO_US
		DECFSZ VEZES,1
		GOTO LACO_VEZES
	RETURN

	INTERVALO_US
		NOP
		NOP
		DECFSZ INTERVALO,1
		GOTO INTERVALO_US
	RETURN



END
