Algoritmo "cont"

// Data atual  : 18/03/2019

//programador: allan stuart virmond
//ide: visualg.2
//exercicio: laco de repeticao com contagem regressiva


Var
// Seção de Declarações das variáveis 
   cont:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para cont de 30 ate 1 passo -1 faca
        escreval("contagem regressiva ",cont)
   fimpara
   escreval
   escreval("contagem finalizada")
Fimalgoritmo