//programador: allan stuart virmond
//professor: fernando maia
//instituicao de ensino: colegio estadual do parana
//disciplina: linguagem de programacao
//ide: visualg.2
//data : 15/03/2018

//exercicio: 
//calculo do indice de massa corporal



algoritmo "IMC"

var
p,a:real
inicio
      escreval("informe seu peso (kg) e depois altura (m): ")
      leia(p,a)
      escreval("IMC: ",p/a^2)
      
fimalgoritmo
