;programador: allan stuart virmond
;professor: winston sen lun fung
;instituicao de ensino: escola superior politecnica uninter
;disciplina: microprocessadores e microcontroladores
;ide: mplab 7
;microcontrolador: pic16f877a
;dev kit: HJ_5G

;exercicio: 
;fazer o motor de passo girar horario e antihorario
;quando aperta um botao o motor gira horario
;quando aperta outro o motor gira anti horario



;TESTE1 WAVE DRIVE
;SOMENTE UMA BOBINA POR VEZ
;TORQUE FRACO
;GIRANDO ANTI HORARIO
;DOIS MOTORES 1 ANTI HORARIO OUTRO HORARIO
;APERTA K1 K2 
;ALTERNA ENTRE HORARIO ANTIHORARIO 
;CADA MOTOR INDIVIDUALMENTE
;*********************  Defini??o do processador *****************************

			#include p16F877A.inc 
			__config _HS_OSC & _WDT_OFF & _LVP_OFF & _PWRTE_ON 

;************************** Mem?ria de programa ******************************
INTERVALO EQU 7EH
VEZES EQU 7FH

CBLOCK 0X20	
		;CRIANDO PONTEIROS A PARTIR DO ENDERECO 0X20
		;ANTES DO ORG SOMENTE A DECLARACAO, 
		;INICIAR APENAS DEPOIS DE ACESSAR O BANCO CORRETO
	BOTAOPRESSIONADO	;PONTEIRO BOTAOPRESSIONADO PARA 0X20
;	CONDICAOC	;PONTEIRO CONDICAOC PARA 0X21
;	CONDICAOM	;PONTEIRO CONDICAOM PARA 0X22
	ENDC

 			ORG	0 

RESET
	NOP             
	GOTO SETUP

;***************************** Interrup??o **********************************
 			ORG 4 

;*************************** Inicio do programa ******************************



SETUP	
	BSF STATUS,RP0
		;CONFIGURA O BIT RP0 DO REGISTRADOR
		;STATUS RP0 PARA 1
		;ACESSA O BANK 1 DE MEMORIA
		;S DE SET   
	MOVLW B'00001111'
		;SALVA ESSE BINARIO NO W
	MOVWF TRISB
		;MANDA O WORK PRO TRISB 
		;CONFIGURANDO COMO ENTRADA 1 NO TRISB
		;OS BOTOES K4-K1

	CLRF TRISD
		;CONFIGURA O TRISD TODO PARA OUTPUT 0

	BCF STATUS,RP0
		;configura bit rp0 do registrador
		;status rp0 para 0, acessa o bank0 de memoria
		;c de clear

	CLRF PORTB
	CLRF PORTD
	CLRF BOTAOPRESSIONADO
	CLRW
		;ZERA ESSES REGISTRADORES



LOOP

	BTFSS PORTB,0
			;verifica o bit posicional 0 DO PORTB
			;e pula se for 1
			;LINHA 3 POR PADRAO
			;SE O BOTAO K1 ESTIVER APERTADO
		GOTO TOGGLEK1
	
		RETORNARTOGGLEK1
	
	BTFSS PORTB,1
			;verifica o bit posicional 0 DO PORTB
			;e pula se for 1
			;LINHA 3 POR PADRAO
			;SE O BOTAO K1 ESTIVER APERTADO
		GOTO TOGGLEK2

		RETORNARTOGGLEK2
	
	BTFSS BOTAOPRESSIONADO,0
		GOTO MOTOR1HORARIO
		GOTO MOTOR1ANTIHORARIO
		RMOTOR1HORARIO
		RMOTOR1ANTIHORARIO

	BTFSS BOTAOPRESSIONADO,1
		GOTO MOTOR2HORARIO
		GOTO MOTOR2ANTIHORARIO
		RMOTOR2HORARIO
		RMOTOR2ANTIHORARIO
	


GOTO LOOP



TOGGLEK1
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR

	BTFSC BOTAOPRESSIONADO,0
	BCF BOTAOPRESSIONADO,0
	
	BTFSS BOTAOPRESSIONADO,0
	BSF BOTAOPRESSIONADO,0
GOTO RETORNARTOGGLEK1

TOGGLEK2
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR
	CALL AGUARDAR

	BTFSC BOTAOPRESSIONADO,1
	BCF BOTAOPRESSIONADO,1
	
	BTFSS BOTAOPRESSIONADO,1
	BSF BOTAOPRESSIONADO,1
GOTO RETORNARTOGGLEK2

MOTOR1HORARIO
	BCF BOTAOPRESSIONADO,0

	MOVLW B'00000001'
	MOVWF PORTD
	CALL AGUARDAR

	MOVLW B'00000010'
	MOVWF PORTD
	CALL AGUARDAR

	MOVLW B'00000100'
	MOVWF PORTD
	CALL AGUARDAR

	MOVLW B'00001000'
	MOVWF PORTD
	CALL AGUARDAR
GOTO RMOTOR1HORARIO

MOTOR1ANTIHORARIO
	BSF BOTAOPRESSIONADO,0

	MOVLW B'00001000'
	MOVWF PORTD
	CALL AGUARDAR

	MOVLW B'00000100'
	MOVWF PORTD
	CALL AGUARDAR

	MOVLW B'00000010'
	MOVWF PORTD
	CALL AGUARDAR

	MOVLW B'00000001'
	MOVWF PORTD
	CALL AGUARDAR
GOTO RMOTOR1ANTIHORARIO

MOTOR2HORARIO
	BCF BOTAOPRESSIONADO,1

	MOVLW B'00010000'
	MOVWF PORTD
	CALL AGUARDAR

	MOVLW B'00100000'
	MOVWF PORTD
	CALL AGUARDAR

	MOVLW B'01000000'
	MOVWF PORTD
	CALL AGUARDAR	

	MOVLW B'10000000'
	MOVWF PORTD
	CALL AGUARDAR
GOTO RMOTOR2HORARIO

MOTOR2ANTIHORARIO
	BSF BOTAOPRESSIONADO,1

	MOVLW B'10000000'
	MOVWF PORTD
	CALL AGUARDAR

	MOVLW B'01000000'
	MOVWF PORTD
	CALL AGUARDAR

	MOVLW B'00100000'
	MOVWF PORTD
	CALL AGUARDAR	

	MOVLW B'00010000'
	MOVWF PORTD
	CALL AGUARDAR
GOTO RMOTOR2ANTIHORARIO



AGUARDAR
	MOVLW B'11111111'
		;CONTROLA O TEMPO
	MOVWF VEZES

	LACO_VEZES
		MOVLW B'11111111'
		MOVWF INTERVALO
		CALL INTERVALO_US
		DECFSZ VEZES,1
		GOTO LACO_VEZES
	RETURN

	INTERVALO_US
		NOP
		NOP
		DECFSZ INTERVALO,1
		GOTO INTERVALO_US
	RETURN



END
