//programador: allan stuart virmond
//professor: fernando maia
//instituicao de ensino: colegio estadual do parana
//disciplina: linguagem de programacao
//ide: visualg.2
//data: 06.03.18

//exercicio: 
//exibe uma saudacao na tela



algoritmo "lpa060318"
// Função :
// Autor :
// Data : 20/4/2010
// Seção de Declarações 
// saudacao simples
var

inicio
// Seção de Comandos
   escreva("Olá sou seu algorítimo")
fimalgoritmo
