//programador: allan stuart virmond
//professor: fernando maia
//instituicao de ensino: colegio estadual do parana
//disciplina: linguagem de programacao
//ide: visualg.2

//exercicio: 
//executa ate acertar a senha



algoritmo "senha"
//roda ate acertar a senha
var
  s:caracter
inicio
  s<-"?"
  enquanto s <> "LP" faca
    escreval ("Senha:")
    leia(s)
  fimenquanto
  escreval("Senha correta!")
fimalgoritmo
