//programador: allan stuart virmond
//professor: fernando maia
//instituicao de ensino: colegio estadual do parana
//disciplina: linguagem de programacao
//ide: visualg.2

//exercicio: 
//tabuada do 7 com laco para



Algoritmo "contagem_para"

Var

   n:inteiro
   
Inicio
   escreval("exercício 1:")
   escreval("visualize abaixo a  tabuada do 7")
     para n de 0 ate 10 passo 1 faca
      escreval ("7 x",n,"=",7*n)
     fimpara
Fimalgoritmo
