//programador: allan stuart virmond
//professor: fernando maia
//instituicao de ensino: colegio estadual do parana
//disciplina: linguagem de programacao
//ide: visualg.2

//exercicio: 
//tabuada do numero escolhido com laco para



algoritmo "exercício 2"


var

    n,nu:inteiro

inicio

   escreval("exercicio 2:")
   escreval("visualize uma determinada tabuada")
   leia(nu)
     para n de 0 ate 10 faca
      escreval (nu," x",n,"=",n*nu)
     fimpara

fimalgoritmo
