//programador: allan stuart virmond
//professor: fernando maia
//instituicao de ensino: colegio estadual do parana
//disciplina: linguagem de programacao
//ide: visualg.2

//exercicio: 
//tabuada em um intervalo definido



algoritmo "exercicio 3"


var

   i,c,f,t:inteiro
   
inicio
   escreva("tabuada:")
   leia(t)
   escreva("inicio:")
   leia(i)
   repita
   escreva("fim:")
   leia(f)
   ate(i<f)
     para c de i ate f faca
       escreval(t," x",c,"=",t*c)
     fimpara
fimalgoritmo
